name: coverage-workflow
on: [push]
jobs:
    run-code-coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                cd angular-unit-tests-example
                npm install
            - run:  |
                cd angular-unit-tests-example
                npm run test-cov
            - name: Add coverage comment
              uses: ScaCap/code-coverage-assistant@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  lcov-file: "./angular-unit-tests-example/coverage/angular-unit-tests-example/lcov.info"
